class Keys {
  static const PROJECT_LIST_ADD_PROJECT_BUTTON_KEY =
      'PROJECT_LIST_ADD_PROJECT_BUTTON_KEY';

  static const PROJECT_FORM_PROJECT_NAME_FIELD_KEY =
      'PROJECT_FORM_PROJECT_NAME_FIELD';
  static const PROJECT_FORM_DEFAULT_CURRENCY_KEY =
      'PROJECT_FORM_DEFAULT_CURRENCY_KEY';
  static const PROJECT_FORM_ADD_EDIT_BUTTON_KEY =
      'PROJECT_FORM_ADD_EDIT_BUTTON_KEY';

  static const DELETE_CONFIRMATION_DELETE_BUTTON =
      'DELETE_CONFIRMATION_DELETE_BUTTON';
  static const DELETE_CONFIRMATION_CANCEL_BUTTON =
      'DELETE_CONFIRMATION_CANCEL_BUTTON';

  static const USER_FORM_NAME_FIELD_KEY =
      'USER_FORM_NAME_FIELD_KEY';
  static const USER_FORM_ADD_EDIT_BUTTON_KEY =
      'USER_FORM_ADD_EDIT_BUTTON_KEY';
}
