class Keys {
  static const PROJECT_LIST_ADD_PROJECT_BUTTON_KEY =
      'PROJECT_LIST_ADD_PROJECT_BUTTON_KEY';

  static const PROJECT_FORM_PROJECT_NAME_FIELD_KEY =
      'PROJECT_FORM_PROJECT_NAME_FIELD';
  static const PROJECT_FORM_DEFAULT_CURRENCY_KEY =
      'PROJECT_FORM_DEFAULT_CURRENCY_KEY';
  static const PROJECT_FORM_ADD_EDIT_BUTTON_KEY =
      'PROJECT_FORM_ADD_EDIT_BUTTON_KEY';
  static const PROJECT_FORM_CANCEL_BUTTON_KEY =
      'PROJECT_FORM_CANCEL_BUTTON_KEY';

  static const PROJECT_DETAILS_USERS_TAB = 'PROJECT_DETAILS_USERS_TAB';
  static const PROJECT_DETAILS_EXPENSES_TAB = 'PROJECT_DETAILS_EXPENSES_TAB';
  static const PROJECT_DETAILS_REPORT_TAB = 'PROJECT_DETAILS_REPORT_TAB';

  static const PROJECT_DETAILS_ADD_USER_BUTTON =
      'PROJECT_DETAILS_ADD_USER_BUTTON';
  static const PROJECT_DETAILS_ADD_EXPENSE_BUTTON =
      'PROJECT_DETAILS_ADD_EXPENSE_BUTTON';

  static const DELETE_CONFIRMATION_DELETE_BUTTON =
      'DELETE_CONFIRMATION_DELETE_BUTTON';
  static const DELETE_CONFIRMATION_CANCEL_BUTTON =
      'DELETE_CONFIRMATION_CANCEL_BUTTON';
  static const ALERT_DIALOG_OK_BUTTON = 'ALERT_DIALOG_OK_BUTTON';

  static const USER_FORM_NAME_FIELD_KEY = 'USER_FORM_NAME_FIELD_KEY';
  static const USER_FORM_ADD_EDIT_BUTTON_KEY = 'USER_FORM_ADD_EDIT_BUTTON_KEY';

  static const EXPENSE_FORM_CURRENCY_KEY = 'EXPENSE_FORM_CURRENCY_KEY';
  static const EXPENSE_FORM_ADD_EDIT_BUTTON_KEY =
      'EXPENSE_FORM_ADD_EDIT_BUTTON_KEY';
  static const EXPENSE_FORM_DESCRIPTION_FIELD_KEY =
      'EXPENSE_FORM_DESCRIPTION_FIELD_KEY';
  static const EXPENSE_FORM_AMOUNT_FIELD_KEY = 'EXPENSE_FORM_AMOUNT_FIELD_KEY';
  static const EXPENSE_FORM_USER_KEY = 'EXPENSE_FORM_USER_KEY';
  static const EXPENSE_FORM_RECEIVERS_FIELD_KEY =
      'EXPENSE_FORM_RECEIVERS_FIELD_KEY';

  static const MULTI_SELECT_CHIP_SELECT_ALL = 'MULTI_SELECT_CHIP_SELECT_ALL';
  static const MULTI_SELECT_CHIP_SELECT_NONE = 'MULTI_SELECT_CHIP_SELECT_NONE';
}
